# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_definition.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service_definition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18service_definition.proto\x12\x04temp\"\x16\n\x05Index\x12\r\n\x05index\x18\x01 \x01(\x05\"_\n\tPositions\x12\n\n\x02p1\x18\x01 \x01(\x01\x12\n\n\x02j1\x18\x02 \x01(\x01\x12\n\n\x02j2\x18\x03 \x01(\x01\x12\n\n\x02j3\x18\x04 \x01(\x01\x12\n\n\x02j4\x18\x05 \x01(\x01\x12\n\n\x02j5\x18\x06 \x01(\x01\x12\n\n\x02j6\x18\x07 \x01(\x01\x32j\n\tMyMessage\x12-\n\x0bGetPosition\x12\x0b.temp.Index\x1a\x0f.temp.Positions\"\x00\x12.\n\x0cSendPosition\x12\x0f.temp.Positions\x1a\x0b.temp.Index\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_definition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDEX']._serialized_start=34
  _globals['_INDEX']._serialized_end=56
  _globals['_POSITIONS']._serialized_start=58
  _globals['_POSITIONS']._serialized_end=153
  _globals['_MYMESSAGE']._serialized_start=155
  _globals['_MYMESSAGE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
