# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_definition_pb2 as service__definition__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_definition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MyMessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPosition = channel.unary_unary(
                '/temp.MyMessage/GetPosition',
                request_serializer=service__definition__pb2.Index.SerializeToString,
                response_deserializer=service__definition__pb2.Positions.FromString,
                _registered_method=True)
        self.SendPosition = channel.unary_unary(
                '/temp.MyMessage/SendPosition',
                request_serializer=service__definition__pb2.Positions.SerializeToString,
                response_deserializer=service__definition__pb2.Index.FromString,
                _registered_method=True)


class MyMessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyMessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=service__definition__pb2.Index.FromString,
                    response_serializer=service__definition__pb2.Positions.SerializeToString,
            ),
            'SendPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPosition,
                    request_deserializer=service__definition__pb2.Positions.FromString,
                    response_serializer=service__definition__pb2.Index.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temp.MyMessage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temp.MyMessage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MyMessage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temp.MyMessage/GetPosition',
            service__definition__pb2.Index.SerializeToString,
            service__definition__pb2.Positions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temp.MyMessage/SendPosition',
            service__definition__pb2.Positions.SerializeToString,
            service__definition__pb2.Index.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
